#define workflow name
name: Test

#event
on:
  push:
    branches:
    - main
#steps to do during the action, with different sub-steps --> different functions each
jobs: 
  build:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Check directory
        run: dir
